java -classpath ./ Silc < test01.sil
java -classpath ./ Silc < test02.sil
java -classpath ./ Silc < test03.sil
java -classpath ./ Silc < test04.sil
java -classpath ./ Silc < test05.sil
java -classpath ./ Silc < test06.sil
java -classpath ./ Silc < test07.sil
java -classpath ./ Silc < test08.sil
java -classpath ./ Silc < test09.sil
java -classpath ./ Silc < test10.sil
java -classpath ./ Silc < test11.sil
java -classpath ./ Silc < test12.sil
java -classpath ./ Silc < test13.sil
java -classpath ./ Silc < test14.sil