#!/bin/sh
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test01.sil
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test02.sil
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test03.sil
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test04.sil
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test05.sil
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test06.sil
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test07.sil
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test08.sil
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test09.sil
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test10.sil
time java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test13.sil
