#!/bin/sh
echo "=== Test01.sil ==="
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test01.sil
echo "=== Test02.sil ==="
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test02.sil
echo "=== Test03.sil ==="
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test03.sil
echo "=== Test04.sil ==="
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test04.sil
echo "=== Test05.sil ==="
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test05.sil
echo "=== Test06.sil ==="
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test06.sil
echo "=== Test07.sil ==="
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test07.sil
echo "=== Test08.sil ==="
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test08.sil
echo "=== Test09.sil ==="
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test09.sil
echo "=== Test10.sil ==="
java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test10.sil
echo "=== Test13.sil ==="
time java -classpath ./bin:./lib/ecj-4.6.1.jar Silt < test13.sil
