/* Generated By:JavaCC: Do not edit this line. CalcVisitor.java Version 5.0 */
package uk.ac.derby.ldi.calcast.parser;

public interface CalcVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTCode node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTCompEqual node, Object data);
  public Object visit(ASTCompNequal node, Object data);
  public Object visit(ASTCompGTE node, Object data);
  public Object visit(ASTCompLTE node, Object data);
  public Object visit(ASTCompGT node, Object data);
  public Object visit(ASTCompLT node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTSubtract node, Object data);
  public Object visit(ASTTimes node, Object data);
  public Object visit(ASTDivide node, Object data);
  public Object visit(ASTUnaryNot node, Object data);
  public Object visit(ASTUnaryPlus node, Object data);
  public Object visit(ASTUnaryMinus node, Object data);
  public Object visit(ASTInteger node, Object data);
  public Object visit(ASTRational node, Object data);
  public Object visit(ASTTrue node, Object data);
  public Object visit(ASTFalse node, Object data);
}
/* JavaCC - OriginalChecksum=373996d95bb376d56be7e54b3bfcbbf9 (do not edit this line) */
