/* Generated By:JavaCC: Do not edit this line. CalcTreeConstants.java Version 5.0 */
package uk.ac.derby.ldi.calcast.parser;

public interface CalcTreeConstants
{
  public int JJTCODE = 0;
  public int JJTVOID = 1;
  public int JJTEXPRESSION = 2;
  public int JJTOR = 3;
  public int JJTAND = 4;
  public int JJTCOMPEQUAL = 5;
  public int JJTCOMPNEQUAL = 6;
  public int JJTCOMPGTE = 7;
  public int JJTCOMPLTE = 8;
  public int JJTCOMPGT = 9;
  public int JJTCOMPLT = 10;
  public int JJTADD = 11;
  public int JJTSUBTRACT = 12;
  public int JJTTIMES = 13;
  public int JJTDIVIDE = 14;
  public int JJTUNARYNOT = 15;
  public int JJTUNARYPLUS = 16;
  public int JJTUNARYMINUS = 17;
  public int JJTINTEGER = 18;
  public int JJTRATIONAL = 19;
  public int JJTTRUE = 20;
  public int JJTFALSE = 21;


  public String[] jjtNodeName = {
    "Code",
    "void",
    "Expression",
    "Or",
    "And",
    "CompEqual",
    "CompNequal",
    "CompGTE",
    "CompLTE",
    "CompGT",
    "CompLT",
    "Add",
    "Subtract",
    "Times",
    "Divide",
    "UnaryNot",
    "UnaryPlus",
    "UnaryMinus",
    "Integer",
    "Rational",
    "True",
    "False",
  };
}
/* JavaCC - OriginalChecksum=3ed4df355815023c9781521491af70e1 (do not edit this line) */
