/* Generated By:JJTree: Do not edit this line. ASTFalse.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=uk.ac.derby.ldi.silc.compiler.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.derby.ldi.silc.parser;

public
class ASTFalse extends SimpleNode {
  public ASTFalse(int id) {
    super(id);
  }

  public ASTFalse(Silc p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SilcVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ac01e8ef140919038589e109191e40f4 (do not edit this line) */
