/* Generated By:JJTree: Do not edit this line. ASTForLoop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=uk.ac.derby.ldi.silc.compiler.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.derby.ldi.silc.parser;

public
class ASTForLoop extends SimpleNode {
  public ASTForLoop(int id) {
    super(id);
  }

  public ASTForLoop(Silc p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SilcVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8db325e6a37f41df063c47b2bd5d39d1 (do not edit this line) */
