/* Generated By:JJTree: Do not edit this line. ASTFnInvoke.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=uk.ac.derby.ldi.silc.compiler.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.derby.ldi.silc.parser;

public
class ASTFnInvoke extends SimpleNode {
  public ASTFnInvoke(int id) {
    super(id);
  }

  public ASTFnInvoke(Silc p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SilcVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3180f39d111e0afa9f66d71eb3bca3f8 (do not edit this line) */
